# permissions for end users to view exchanges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exchange-viewer-role
rules:
- apiGroups:
  - rabbitmq.com
  resources:
  - exchanges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - exchanges/status
  verbs:
  - get
