# permissions for end users to view permissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: permission-viewer-role
rules:
- apiGroups:
  - rabbitmq.com
  resources:
  - permissions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - permissions/status
  verbs:
  - get
