# permissions for end users to edit permissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: permission-editor-role
rules:
- apiGroups:
  - rabbitmq.com
  resources:
  - permissions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - permissions/status
  verbs:
  - get
