apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: federations.rabbitmq.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1", "v1beta1"]
      clientConfig:
        caBundle: Cg==
        service:
          namespace: system
          name: webhook-service
          path: /convert
